name = "price-tracker"
type = "javascript"
account_id = "cab49d8e81aa534e8d2b9ba3e567bb4b"
workers_dev = true
main = "app.js"
compatibility_date = "2025-08-03"

[env.production]
# Uncomment and set your production settings here
# route = "example.com/*"
# zone_id = ""
